[package]
name = "DatapackGen"
version = "0.0.0"
description = "Gaia - Minecraft Data and Resourcepack Generator"
authors = ["The Lady Dawn"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"
serde_repr = "0.1"
serde_with = "3.7"

zip = "2.2"

iced = { version = "0.13.1", features = ["highlighter", "tokio", "debug"] }

tokio = { version = "1.43.0", features = ["fs"] }

rfd = "0.13"